baseURL = "https://NaofalMufid.github.io"
title = "Naofal Mufid"
languageCode = "en-us"
copyright = "Copyright 2018 valno.val"
themesdir = "themes"
theme = "hugo_eiio"
Paginate=7
PaginatePath="page"
pygmentsusecclasses = true
disqusShortname = "valnovcc"
googleAnalytics='US-XXXXXX-XX'

[taxonomies]
    category = "categories"
    tag = "tags"

[params]
    description = "Secerah malam sesilau kabut"
    author = "Valno"
    github = "https://github.com/NaofalMufid"
    securityPolicy = false
    footerRight = "Hati Sutji"
    addthisID = "addthis.com"
    
    [[params.navlinks]]
	name = "About"
	url = "about/"
    
[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"